"""Create emotion analytics tables

Revision ID: 08d55e7a5f2c
Revises: add_oauth_fields
Create Date: 2025-12-13 02:39:17.988938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08d55e7a5f2c'
down_revision = 'add_oauth_fields'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_exercise_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('progress_percentage', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('last_practiced_at', sa.DateTime(), nullable=True),
    sa.Column('times_completed', sa.Integer(), nullable=True),
    sa.Column('total_time_spent_minutes', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'exercise_id', name='unique_user_exercise')
    )
    with op.batch_alter_table('user_exercise_progress', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_exercise_progress_exercise_id'), ['exercise_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_exercise_progress_user_id'), ['user_id'], unique=False)

    op.create_table('clinical_emotion_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('reviewed_by_doctor_id', sa.Integer(), nullable=True),
    sa.Column('dominant_emotion', sa.String(length=50), nullable=False),
    sa.Column('emotional_changes', sa.String(length=500), nullable=True),
    sa.Column('precipitants', sa.JSON(), nullable=True),
    sa.Column('automatic_thoughts', sa.JSON(), nullable=True),
    sa.Column('maladaptive_behaviors', sa.JSON(), nullable=True),
    sa.Column('core_beliefs', sa.JSON(), nullable=True),
    sa.Column('suicidal_ideation', sa.Boolean(), nullable=True),
    sa.Column('self_harm_risk', sa.Boolean(), nullable=True),
    sa.Column('severity_level', sa.String(length=20), nullable=False),
    sa.Column('requires_immediate_intervention', sa.Boolean(), nullable=True),
    sa.Column('risk_notes', sa.Text(), nullable=True),
    sa.Column('interventions_used', sa.JSON(), nullable=True),
    sa.Column('recommended_interventions', sa.JSON(), nullable=True),
    sa.Column('next_steps', sa.JSON(), nullable=True),
    sa.Column('follow_up_timeline', sa.String(length=100), nullable=True),
    sa.Column('clinical_summary', sa.Text(), nullable=False),
    sa.Column('analyzed_at', sa.DateTime(), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('doctor_reviewed', sa.Boolean(), nullable=True),
    sa.Column('doctor_notes', sa.Text(), nullable=True),
    sa.Column('doctor_reviewed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_doctor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clinical_emotion_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clinical_emotion_reports_analyzed_at'), ['analyzed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_clinical_emotion_reports_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_clinical_emotion_reports_session_id'), ['session_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_clinical_emotion_reports_severity_level'), ['severity_level'], unique=False)
        batch_op.create_index(batch_op.f('ix_clinical_emotion_reports_suicidal_ideation'), ['suicidal_ideation'], unique=False)

    op.create_table('doctor_availability',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('doctor_availability', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_doctor_availability_doctor_id'), ['doctor_id'], unique=False)

    op.create_table('doctor_time_off',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('doctor_time_off', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_doctor_time_off_doctor_id'), ['doctor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_doctor_time_off_end_date'), ['end_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_doctor_time_off_start_date'), ['start_date'], unique=False)

    op.create_table('session_emotion_analytics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('total_messages', sa.Integer(), nullable=True),
    sa.Column('user_messages', sa.Integer(), nullable=True),
    sa.Column('dominant_emotion', sa.String(length=50), nullable=False),
    sa.Column('emotional_breakdown', sa.JSON(), nullable=True),
    sa.Column('overall_sentiment', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('intensity_average', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('emotional_progression', sa.JSON(), nullable=True),
    sa.Column('triggers_primary', sa.String(length=200), nullable=True),
    sa.Column('triggers_secondary', sa.JSON(), nullable=True),
    sa.Column('risk_level', sa.String(length=20), nullable=True),
    sa.Column('risk_flags', sa.JSON(), nullable=True),
    sa.Column('trend', sa.String(length=20), nullable=True),
    sa.Column('simple_summary', sa.Text(), nullable=True),
    sa.Column('analyzed_at', sa.DateTime(), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('session_emotion_analytics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_session_emotion_analytics_analyzed_at'), ['analyzed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_session_emotion_analytics_dominant_emotion'), ['dominant_emotion'], unique=False)
        batch_op.create_index(batch_op.f('ix_session_emotion_analytics_risk_level'), ['risk_level'], unique=False)
        batch_op.create_index(batch_op.f('ix_session_emotion_analytics_session_id'), ['session_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_session_emotion_analytics_user_id'), ['user_id'], unique=False)

    op.create_table('doctor_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('appointment_id', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('review_text', sa.Text(), nullable=True),
    sa.Column('professionalism', sa.Integer(), nullable=True),
    sa.Column('communication', sa.Integer(), nullable=True),
    sa.Column('effectiveness', sa.Integer(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('is_anonymous', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor_profiles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('doctor_reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_doctor_reviews_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_doctor_reviews_doctor_id'), ['doctor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_doctor_reviews_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctor_reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_doctor_reviews_user_id'))
        batch_op.drop_index(batch_op.f('ix_doctor_reviews_doctor_id'))
        batch_op.drop_index(batch_op.f('ix_doctor_reviews_created_at'))

    op.drop_table('doctor_reviews')
    with op.batch_alter_table('session_emotion_analytics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_session_emotion_analytics_user_id'))
        batch_op.drop_index(batch_op.f('ix_session_emotion_analytics_session_id'))
        batch_op.drop_index(batch_op.f('ix_session_emotion_analytics_risk_level'))
        batch_op.drop_index(batch_op.f('ix_session_emotion_analytics_dominant_emotion'))
        batch_op.drop_index(batch_op.f('ix_session_emotion_analytics_analyzed_at'))

    op.drop_table('session_emotion_analytics')
    with op.batch_alter_table('doctor_time_off', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_doctor_time_off_start_date'))
        batch_op.drop_index(batch_op.f('ix_doctor_time_off_end_date'))
        batch_op.drop_index(batch_op.f('ix_doctor_time_off_doctor_id'))

    op.drop_table('doctor_time_off')
    with op.batch_alter_table('doctor_availability', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_doctor_availability_doctor_id'))

    op.drop_table('doctor_availability')
    with op.batch_alter_table('clinical_emotion_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clinical_emotion_reports_suicidal_ideation'))
        batch_op.drop_index(batch_op.f('ix_clinical_emotion_reports_severity_level'))
        batch_op.drop_index(batch_op.f('ix_clinical_emotion_reports_session_id'))
        batch_op.drop_index(batch_op.f('ix_clinical_emotion_reports_patient_id'))
        batch_op.drop_index(batch_op.f('ix_clinical_emotion_reports_analyzed_at'))

    op.drop_table('clinical_emotion_reports')
    with op.batch_alter_table('user_exercise_progress', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_exercise_progress_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_exercise_progress_exercise_id'))

    op.drop_table('user_exercise_progress')
    # ### end Alembic commands ###
