"""Change subscription_plan to integer

Revision ID: 20236626d9e7
Revises: 25b7d258527e
Create Date: 2025-12-13 14:40:30.371623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20236626d9e7'
down_revision = '25b7d258527e'
branch_labels = None
depends_on = None


def upgrade():
    # First convert string data to integers using PostgreSQL USING clause
    op.execute("""
        ALTER TABLE users 
        ALTER COLUMN subscription_plan 
        TYPE INTEGER 
        USING CASE 
            WHEN subscription_plan ~ '^[0-9]+$' THEN subscription_plan::integer 
            ELSE NULL 
        END
    """)
    
    # Add foreign key constraint
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_users_subscription_plan', 'plans', ['subscription_plan'], ['id'])


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('subscription_plan',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###
