"""Add appointment_id to chat_sessions

Revision ID: 25b7d258527e
Revises: add_appointment_payment_link
Create Date: 2025-12-13 11:46:44.999617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25b7d258527e'
down_revision = 'add_appointment_payment_link'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('appointment_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_chat_sessions_appointment_id'), ['appointment_id'], unique=False)
        batch_op.create_foreign_key(None, 'appointments', ['appointment_id'], ['id'])

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.alter_column('payment_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'subscription'::character varying"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.alter_column('payment_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'subscription'::character varying"))

    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_chat_sessions_appointment_id'))
        batch_op.drop_column('appointment_id')

    # ### end Alembic commands ###
